# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: '', folder: 'pages', file: '.html'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/'}
- {icon: 'facebook', link: 'https://www.facebook.com/'}
- {icon: 'instagram', link: 'https://instagram.com/'}
- {icon: 'envelope', link: 'mailto:'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: ''

related_posts: ''

post_date_prefix: ''
